/*ServerEvents.recipes(event => {
    // 统一所有矿物相关
    // 宝石/gem
    event.replaceInput({}, '#forge:gems/ruby', 'alltheores:ruby')
    event.replaceInput({}, '#forge:gems/peridot', 'alltheores:peridot')
    event.replaceInput({}, '#forge:gems/sapphire', 'alltheores:sapphire')
    // 锭/ingot
    event.replaceInput({}, '#forge:ingots/aluminum', 'alltheores:aluminum_ingot')
    event.replaceInput({}, '#forge:ingots/lead', 'alltheores:lead_ingot')
    event.replaceInput({}, '#forge:ingots/nickel', 'alltheores:nickel_ingot')
    event.replaceInput({}, '#forge:ingots/osmium', 'alltheores:osmium_ingot')
    event.replaceInput({}, '#forge:ingots/platinum', 'alltheores:platinum_ingot')
    event.replaceInput({}, '#forge:ingots/silver', 'alltheores:silver_ingot')
    event.replaceInput({}, '#forge:ingots/tin', 'alltheores:tin_ingot')
    event.replaceInput({}, '#forge:ingots/uranium', 'alltheores:uranium_ingot')
    event.replaceInput({}, '#forge:ingots/zinc', 'alltheores:zinc_ingot')
    event.replaceInput({}, '#forge:ingots/iridium', 'alltheores:iridium_ingot')
    event.replaceInput({}, '#forge:ingots/steel', 'alltheores:steel_ingot')
    event.replaceInput({}, '#forge:ingots/invar', 'alltheores:invar_ingot')
    event.replaceInput({}, '#forge:ingots/electrum', 'alltheores:electrum_ingot')
    event.replaceInput({}, '#forge:ingots/bronze', 'alltheores:bronze_ingot')
    event.replaceInput({}, '#forge:ingots/enderium', 'alltheores:enderium_ingot')
    event.replaceInput({}, '#forge:ingots/lumium', 'alltheores:lumium_ingot')
    event.replaceInput({}, '#forge:ingots/signalum', 'alltheores:signalum_ingot')
    event.replaceInput({}, '#forge:ingots/constantan', 'alltheores:constantan_ingot')
    event.replaceInput({}, '#forge:ingots/brass', 'alltheores:brass_ingot')
    // 粒/nugget
    event.replaceInput({}, '#forge:nuggets/aluminum', 'alltheores:aluminum_nugget')
    event.replaceInput({}, '#forge:nuggets/lead', 'alltheores:lead_nugget')
    event.replaceInput({}, '#forge:nuggets/nickel', 'alltheores:nickel_nugget')
    event.replaceInput({}, '#forge:nuggets/osmium', 'alltheores:osmium_nugget')
    event.replaceInput({}, '#forge:nuggets/platinum', 'alltheores:platinum_nugget')
    event.replaceInput({}, '#forge:nuggets/silver', 'alltheores:silver_nugget')
    event.replaceInput({}, '#forge:nuggets/tin', 'alltheores:tin_nugget')
    event.replaceInput({}, '#forge:nuggets/uranium', 'alltheores:uranium_nugget')
    event.replaceInput({}, '#forge:nuggets/zinc', 'alltheores:zinc_nugget')
    event.replaceInput({}, '#forge:nuggets/iridium', 'alltheores:iridium_nugget')
    event.replaceInput({}, '#forge:nuggets/steel', 'alltheores:steel_nugget')
    event.replaceInput({}, '#forge:nuggets/invar', 'alltheores:invar_nugget')
    event.replaceInput({}, '#forge:nuggets/electrum', 'alltheores:electrum_nugget')
    event.replaceInput({}, '#forge:nuggets/bronze', 'alltheores:bronze_nugget')
    event.replaceInput({}, '#forge:nuggets/enderium', 'alltheores:enderium_nugget')
    event.replaceInput({}, '#forge:nuggets/lumium', 'alltheores:lumium_nugget')
    event.replaceInput({}, '#forge:nuggets/signalum', 'alltheores:signalum_nugget')
    event.replaceInput({}, '#forge:nuggets/constantan', 'alltheores:constantan_nugget')
    event.replaceInput({}, '#forge:nuggets/brass', 'alltheores:brass_nugget')
    // 块/block
    event.replaceInput({}, '#forge:blocks/aluminum', 'alltheores:aluminum_block')
    event.replaceInput({}, ['#forge:blocks/lead', '#forge:storage_blocks/lead'], 'alltheores:lead_block')
    event.replaceInput({}, ['#forge:blocks/nickel', '#forge:storage_blocks/nickel'], 'alltheores:nickel_block')
    event.replaceInput({}, '#forge:blocks/osmium', 'alltheores:osmium_block')
    event.replaceInput({}, '#forge:blocks/platinum', 'alltheores:platinum_block')
    event.replaceInput({}, ['#forge:blocks/silver', '#forge:storage_blocks/silver'], 'alltheores:silver_block')
    event.replaceInput({}, ['#forge:blocks/tin', '#forge:storage_blocks/tin'], 'alltheores:tin_block')
    event.replaceInput({}, '#forge:blocks/uranium', 'alltheores:uranium_block')
    event.replaceInput({}, '#forge:blocks/zinc', 'alltheores:zinc_block')
    event.replaceInput({}, '#forge:blocks/iridium', 'alltheores:iridium_block')
    event.replaceInput({}, ['#forge:blocks/steel', '#forge:storage_blocks/steel'], 'alltheores:steel_block')
    event.replaceInput({}, ['#forge:blocks/invar', '#forge:storage_blocks/invar'], 'alltheores:invar_block')
    event.replaceInput({}, ['#forge:blocks/electrum', '#forge:storage_blocks/electrum'], 'alltheores:electrum_block')
    event.replaceInput({}, ['#forge:blocks/bronze', '#forge:storage_blocks/bronze'], 'alltheores:bronze_block')
    event.replaceInput({}, ['#forge:blocks/enderium', '#forge:storage_blocks/enderium'], 'alltheores:enderium_block')
    event.replaceInput({}, ['#forge:blocks/lumium', '#forge:storage_blocks/lumium'], 'alltheores:lumium_block')
    event.replaceInput({}, ['#forge:blocks/signalum', '#forge:storage_blocks/signalum'], 'alltheores:signalum_block')
    event.replaceInput({}, ['#forge:blocks/constantan', '#forge:storage_blocks/constantan'], 'alltheores:constantan_block')
    event.replaceInput({}, ['#forge:blocks/brass', '#forge:storage_blocks/brass'], 'alltheores:brass_block')
    event.replaceInput({}, '#forge:storage_blocks/ruby', 'alltheores:ruby_block')
    event.replaceInput({}, '#forge:storage_blocks/peridot', 'alltheores:peridot_block')
    event.replaceInput({}, '#forge:storage_blocks/sapphire', 'alltheores:sapphire_block')
    // 粗矿/raw
    event.replaceInput({}, '#forge:raw_materials/aluminum', 'alltheores:raw_aluminum')
    event.replaceInput({}, '#forge:raw_materials/lead', 'alltheores:raw_lead')
    event.replaceInput({}, '#forge:raw_materials/nickel', 'alltheores:raw_nickel')
    event.replaceInput({}, '#forge:raw_materials/osmium', 'alltheores:raw_osmium')
    event.replaceInput({}, '#forge:raw_materials/platinum', 'alltheores:raw_platinum')
    event.replaceInput({}, '#forge:raw_materials/silver', 'alltheores:raw_silver')
    event.replaceInput({}, '#forge:raw_materials/tin', 'alltheores:raw_tin')
    event.replaceInput({}, '#forge:raw_materials/uranium', 'alltheores:raw_uranium')
    event.replaceInput({}, '#forge:raw_materials/zinc', 'alltheores:raw_zinc')
    event.replaceInput({}, '#forge:raw_materials/iridium', 'alltheores:raw_iridium')
    // 粗矿块/storage_raw
    event.replaceInput({}, '#forge:storage_blocks/raw_aluminum', 'alltheores:raw_aluminum_block')
    event.replaceInput({}, '#forge:storage_blocks/raw_lead', 'alltheores:raw_lead_block')
    event.replaceInput({}, '#forge:storage_blocks/raw_nickel', 'alltheores:raw_nickel_block')
    event.replaceInput({}, '#forge:storage_blocks/raw_osmium', 'alltheores:raw_osmium_block')
    event.replaceInput({}, '#forge:storage_blocks/raw_platinum', 'alltheores:raw_platinum_block')
    event.replaceInput({}, '#forge:storage_blocks/raw_silver', 'alltheores:raw_silver_block')
    event.replaceInput({}, '#forge:storage_blocks/raw_uranium', 'alltheores:raw_uranium_block')
    event.replaceInput({}, '#forge:storage_blocks/raw_zinc', 'alltheores:raw_zinc_block')
    event.replaceInput({}, '#forge:storage_blocks/raw_iridium', 'alltheores:raw_iridium_block')
    event.replaceInput({}, 'alltheores:raw_iridium_block', 'alltheores:raw_tin_block')
    // 粉/dust
    event.replaceInput({}, '#forge:dusts/aluminum', 'alltheores:aluminum_dust')
    event.replaceInput({}, '#forge:dusts/lead', 'alltheores:lead_dust')
    event.replaceInput({}, '#forge:dusts/nickel', 'alltheores:nickel_dust')
    event.replaceInput({}, '#forge:dusts/osmium', 'alltheores:osmium_dust')
    event.replaceInput({}, '#forge:dusts/platinum', 'alltheores:platinum_dust')
    event.replaceInput({}, '#forge:dusts/silver', 'alltheores:silver_dust')
    event.replaceInput({}, '#forge:dusts/tin', 'alltheores:tin_dust')
    event.replaceInput({}, '#forge:dusts/uranium', 'alltheores:uranium_dust')
    event.replaceInput({}, '#forge:dusts/zinc', 'alltheores:zinc_dust')
    event.replaceInput({}, '#forge:dusts/iridium', 'alltheores:iridium_dust')
    event.replaceInput({}, '#forge:dusts/steel', 'alltheores:steel_dust')
    event.replaceInput({}, '#forge:dusts/invar', 'alltheores:invar_dust')
    event.replaceInput({}, '#forge:dusts/electrum', 'alltheores:electrum_dust')
    event.replaceInput({}, '#forge:dusts/bronze', 'alltheores:bronze_dust')
    event.replaceInput({}, '#forge:dusts/enderium', 'alltheores:enderium_dust')
    event.replaceInput({}, '#forge:dusts/lumium', 'alltheores:lumium_dust')
    event.replaceInput({}, '#forge:dusts/signalum', 'alltheores:signalum_dust')
    event.replaceInput({}, '#forge:dusts/constantan', 'alltheores:constantan_dust')
    event.replaceInput({}, '#forge:dusts/brass', 'alltheores:brass_dust')
    event.replaceInput({}, '#forge:dusts/ruby', 'alltheores:ruby_dust')
    event.replaceInput({}, '#forge:dusts/peridot', 'alltheores:peridot_dust')
    event.replaceInput({}, '#forge:dusts/sapphire', 'alltheores:sapphire_dust')
    event.replaceInput({}, '#forge:dusts/iron', 'alltheores:iron_dust')
    event.replaceInput({}, '#forge:dusts/copper', 'alltheores:copper_dust')
    event.replaceInput({}, '#forge:dusts/gold', 'alltheores:gold_dust')
    event.replaceInput({}, '#forge:dusts/diamond', 'alltheores:diamond_dust')
    event.replaceInput({}, '#forge:dusts/netherite', 'alltheores:netherite_dust')
    event.replaceInput({}, '#forge:dusts/coal', 'mekanism:dust_coal')
    event.replaceInput({}, '#forge:dusts/emerald', 'mekanism:dust_emerald')
    event.replaceInput({}, '#forge:dusts/lapis', 'mekanism:dust_lapis_lazuli')
    event.replaceInput({}, '#forge:dusts/obsidian', 'mekanism:dust_obsidian')
    event.replaceInput({}, '#forge:dusts/wood', 'mekanism:sawdust')
    event.replaceInput({}, '#forge:dusts/ender_pearl', 'ae2:ender_dust')
    //
    console.info('矿物输入大统一！/sdjge')
    // 棒/rod
    event.replaceInput({}, '#forge:rods/aluminum', 'alltheores:aluminum_rod')
    event.replaceInput({}, '#forge:rods/lead', 'alltheores:lead_rod')
    event.replaceInput({}, '#forge:rods/nickel', 'alltheores:nickel_rod')
    event.replaceInput({}, '#forge:rods/osmium', 'alltheores:osmium_rod')
    event.replaceInput({}, '#forge:rods/platinum', 'alltheores:platinum_rod')
    event.replaceInput({}, '#forge:rods/silver', 'alltheores:silver_rod')
    event.replaceInput({}, '#forge:rods/tin', 'alltheores:tin_rod')
    event.replaceInput({}, '#forge:rods/uranium', 'alltheores:uranium_rod')
    event.replaceInput({}, '#forge:rods/zinc', 'alltheores:zinc_rod')
    event.replaceInput({}, '#forge:rods/iridium', 'alltheores:iridium_rod')
    event.replaceInput({}, '#forge:rods/steel', 'alltheores:steel_rod')
    event.replaceInput({}, '#forge:rods/invar', 'alltheores:invar_rod')
    event.replaceInput({}, '#forge:rods/electrum', 'alltheores:electrum_rod')
    event.replaceInput({}, '#forge:rods/bronze', 'alltheores:bronze_rod')
    event.replaceInput({}, '#forge:rods/enderium', 'alltheores:enderium_rod')
    event.replaceInput({}, '#forge:rods/lumium', 'alltheores:lumium_rod')
    event.replaceInput({}, '#forge:rods/signalum', 'alltheores:signalum_rod')
    event.replaceInput({}, '#forge:rods/constantan', 'alltheores:constantan_rod')
    event.replaceInput({}, '#forge:rods/brass', 'alltheores:brass_rod')
    event.replaceInput({}, '#forge:rods/diamond', 'alltheores:diamond_rod')
    event.replaceInput({}, '#forge:rods/iron', 'alltheores:iron_rod')
    event.replaceInput({}, '#forge:rods/gold', 'alltheores:gold_rod')
    event.replaceInput({}, '#forge:rods/copper', 'alltheores:copper_rod')
    // 齿轮/gear
    event.replaceInput({}, '#forge:gears/aluminum', 'alltheores:aluminum_gear')
    event.replaceInput({}, '#forge:gears/lead', 'alltheores:lead_gear')
    event.replaceInput({}, '#forge:gears/nickel', 'alltheores:nickel_gear')
    event.replaceInput({}, '#forge:gears/osmium', 'alltheores:osmium_gear')
    event.replaceInput({}, '#forge:gears/platinum', 'alltheores:platinum_gear')
    event.replaceInput({}, '#forge:gears/silver', 'alltheores:silver_gear')
    event.replaceInput({}, '#forge:gears/tin', 'alltheores:tin_gear')
    event.replaceInput({}, '#forge:gears/uranium', 'alltheores:uranium_gear')
    event.replaceInput({}, '#forge:gears/zinc', 'alltheores:zinc_gear')
    event.replaceInput({}, '#forge:gears/iridium', 'alltheores:iridium_gear')
    event.replaceInput({}, '#forge:gears/steel', 'alltheores:steel_gear')
    event.replaceInput({}, '#forge:gears/invar', 'alltheores:invar_gear')
    event.replaceInput({}, '#forge:gears/electrum', 'alltheores:electrum_gear')
    event.replaceInput({}, '#forge:gears/bronze', 'alltheores:bronze_gear')
    event.replaceInput({}, '#forge:gears/enderium', 'alltheores:enderium_gear')
    event.replaceInput({}, '#forge:gears/lumium', 'alltheores:lumium_gear')
    event.replaceInput({}, '#forge:gears/signalum', 'alltheores:signalum_gear')
    event.replaceInput({}, '#forge:gears/constantan', 'alltheores:constantan_gear')
    event.replaceInput({}, '#forge:gears/brass', 'alltheores:brass_gear')
    event.replaceInput({}, '#forge:gears/diamond', 'alltheores:diamond_gear')
    event.replaceInput({}, '#forge:gears/iron', 'alltheores:iron_gear')
    event.replaceInput({}, '#forge:gears/gold', 'alltheores:gold_gear')
    event.replaceInput({}, '#forge:gears/copper', 'alltheores:copper_gear')
    // 板/plate
    event.replaceInput({}, '#forge:plates/aluminum', 'alltheores:aluminum_plate')
    event.replaceInput({}, '#forge:plates/lead', 'alltheores:lead_plate')
    event.replaceInput({}, '#forge:plates/nickel', 'alltheores:nickel_plate')
    event.replaceInput({}, '#forge:plates/osmium', 'alltheores:osmium_plate')
    event.replaceInput({}, '#forge:plates/platinum', 'alltheores:platinum_plate')
    event.replaceInput({}, '#forge:plates/silver', 'alltheores:silver_plate')
    event.replaceInput({}, '#forge:plates/tin', 'alltheores:tin_plate')
    event.replaceInput({}, '#forge:plates/uranium', 'alltheores:uranium_plate')
    event.replaceInput({}, '#forge:plates/zinc', 'alltheores:zinc_plate')
    event.replaceInput({}, '#forge:plates/iridium', 'alltheores:iridium_plate')
    event.replaceInput({}, '#forge:plates/steel', 'alltheores:steel_plate')
    event.replaceInput({}, '#forge:plates/invar', 'alltheores:invar_plate')
    event.replaceInput({}, '#forge:plates/electrum', 'alltheores:electrum_plate')
    event.replaceInput({}, '#forge:plates/bronze', 'alltheores:bronze_plate')
    event.replaceInput({}, '#forge:plates/enderium', 'alltheores:enderium_plate')
    event.replaceInput({}, '#forge:plates/lumium', 'alltheores:lumium_plate')
    event.replaceInput({}, '#forge:plates/signalum', 'alltheores:signalum_plate')
    event.replaceInput({}, '#forge:plates/constantan', 'alltheores:constantan_plate')
    event.replaceInput({}, '#forge:plates/brass', 'alltheores:brass_plate')
    event.replaceInput({}, '#forge:plates/diamond', 'alltheores:diamond_plate')
    event.replaceInput({}, '#forge:plates/iron', 'alltheores:iron_plate')
    event.replaceInput({}, '#forge:plates/gold', 'alltheores:gold_plate')
    event.replaceInput({}, '#forge:plates/copper', 'alltheores:copper_plate')
})*/