
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables certain types
	[general.types]

		[general.types.leaves_type]

			[general.types.leaves_type.forbidden_arcanus]
				aurum = true
				nuggety_aurum = true

			[general.types.leaves_type.integrateddynamics]
				menril = true

			[general.types.leaves_type.mythicbotany]
				dreamwood = true

			[general.types.leaves_type.ars_nouveau]
				blue_archwood = true
				green_archwood = true
				purple_archwood = true
				red_archwood = true

			[general.types.leaves_type.naturesaura]
				ancient = true
				golden = true

			[general.types.leaves_type.thermal]
				rubberwood = true

			[general.types.leaves_type.occultism]
				otherworld = true

			[general.types.leaves_type.create_dd]
				rubber = true

			[general.types.leaves_type.eidolon]
				illwood = true

			[general.types.leaves_type.aether]
				skyroot = true
				golden_oak = true
				crystal = true
				crystal_fruit = true
				holiday = true
				decorated_holiday = true

			[general.types.leaves_type.biomemakeover]
				blighted_balsa = true
				willow = true
				swamp_cypress = true
				ancient_oak = true

			[general.types.leaves_type.quark]
				ancient = true
				blue_blossom = true
				lavender_blossom = true
				orange_blossom = true
				yellow_blossom = true
				red_blossom = true

			[general.types.leaves_type.ars_elemental]
				yellow_archwood = true

		[general.types.wood_type]

			[general.types.wood_type.forbidden_arcanus]
				aurum = true
				edelwood = true

			[general.types.wood_type.ars_nouveau]
				archwood = true

			[general.types.wood_type.quark]
				azalea = true
				ancient = true
				blossom = true

			[general.types.wood_type.thermal]
				rubberwood = true

			[general.types.wood_type.create_dd]
				rose = true
				smoked = true
				spirit = true
				rubber = true

			[general.types.wood_type.eidolon]
				illwood = true

			[general.types.wood_type.aether]
				skyroot = true

			[general.types.wood_type.biomemakeover]
				blighted_balsa = true
				willow = true
				swamp_cypress = true
				ancient_oak = true

			[general.types.wood_type.enlightened_end]
				indigo = true
				cerulean = true

	#Disables specific entries
	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.create]
				window_pane = true
				window = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

