#自动调整摄像机位，以避免阻挡视线
auto_switch_camera_offset_type = true
#是否显示准星
do_render_crosshair = true
#玩家在屏幕中的水平偏移，0表示屏幕中间，1表示边缘（左或右）
#Range: 0.0 ~ 1.0
camera_offset_ratio_x = 0.5
#玩家在屏幕中的垂直偏移，0表示屏幕中间，1表示屏幕底部边缘
#Range: 0.0 ~ 1.0
camera_offset_ratio_y = 0.372
#使用头顶机位时，玩家在屏幕中的垂直偏移，0表示屏幕中间，1表示屏幕底部边缘
#Range: 0.0 ~ 1.0
camera_offset_ratio_top = 0.373
#瞄准时相机视线与玩家视线的距离
#Range: 0.0 ~ 4.0
aim_camera_offset_distance = 0.7
#使用头顶机位瞄准时，相机视线与玩家视线的距离
#Range: 0.0 ~ 4.0
aim_camera_offset_distance_top = 0.6
#较近距离下相机离玩家的最大距离
#Range: 1.0 ~ 64.0
camera_max_distance_closer = 1.6
#较远距离下相机离玩家的最大距离
#Range: 1.0 ~ 64.0
camera_max_distance_farther = 4.0
#玩家眼睛平滑移动速度系数（水平方向）
#系数 a = k^(1/t)
#表示每经过 t 秒，到目标的距离衰变为原来的 k 倍。
#Range: 0.0 ~ 1.0
smooth_eye_speed_xz = 8.0E-4
#玩家眼睛平滑移动速度系数（垂直方向）
#系数 a = k^(1/t)
#表示每经过 t 秒，到目标的距离衰变为原来的 k 倍。
#Range: 0.0 ~ 1.0
smooth_eye_speed_y = 0.04
#相机远离玩家的速度系数
#Range: 0.0 ~ 1.0
move_to_surface_speed = 0.5
#相机偏移量平滑变化的速度系数，算法同上
#Range: 0.0 ~ 1.0
camera_offset_update_speed = 0.002

